add_newline = true
format = """
$directory$git_branch$git_status$nodejs$elixir$erlang
$character
"""

[directory]
style = "bold cyan"

[character]
success_symbol = "[âžœ](bold green) "
error_symbol = "[âœ—](bold red) "

[git_branch]
symbol = "  "
style = "bold yellow"
format = "[$symbol$branch]($style)"

[git_status]
style = "bold purple"
format = "([$all_status$ahead_behind]($style))"
ahead = "â‡¡"
behind = "â‡£"
staged = "+"
modified = "!"
untracked = "?"
